# validator: https://ci.appveyor.com/tools/validate-yaml

version: "{build}"

environment:
  GCLOUD_CREDENTIALS_SALT:
    secure: "tmDQ9iBheiMMWuKKqA/l7U0kC+S2yFeI05B47pGaHTs="
  GCLOUD_CREDENTIALS_KEY:
    secure: "O5HZHcvH48vEP5zAhmhJxbTSohl+6TVVK5hWKKFWwFQBX3cqCsW355pQrS5LGUV9qZ3J34hViLnGcArSEATLiS309BnIsvouH8TaJU99iaA="
  GCLOUD_CREDENTIALS_IV:
    secure: "mXNwsLAU0N1u1oFv4e/QwF6HfMCT39c3La/pniJTgOaQB2Y3LvoPWDvU5JbhF4yQ"
  GITHUB_ACCESS_TOKEN:
    secure: "fcDy5AgkBH9bKqdsbwv9piWbN6ksoUKk+iky/DQmk3YG3UNl68BegfkYUzSF3rJ7"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_GENERATOR_PLATFORM: Win32
      RUST_TARGET: i686-pc-windows-msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_GENERATOR_PLATFORM: x64
      RUST_TARGET: x86_64-pc-windows-msvc

branches:
  only:
    - master
    - nightly

matrix:
  fast_finish: true

clone_folder: c:\projects\ja2-stracciatella
clone_depth: 1

skip_commits:
  # appveyor only searches for tags in the first line by default
  message: /\[ci skip\]/

init:
  - ps: $env:PUBLISH_BINARY = "false";
  - ps: $env:BUILD_TYPE = "Debug";

  - ps: $env:CI_REF = "refs/heads/${env:APPVEYOR_REPO_BRANCH}";
  - ps: >
        if (Test-Path Env:\APPVEYOR_PULL_REQUEST_NUMBER) {
          $env:PUBLISH_BINARY = "true";
          $env:PUBLISH_DIR = "pull-requests/${env:APPVEYOR_PULL_REQUEST_NUMBER}/";
          $env:VERSION_TAG = "${env:APPVEYOR_PULL_REQUEST_NUMBER}pullrequest";
          $env:CI_REF = "refs/pull/${env:APPVEYOR_PULL_REQUEST_NUMBER}";
        }
        true;
  - ps: >
        if ("$env:APPVEYOR_REPO_BRANCH" -eq "nightly") {
          $env:BUILD_TYPE = "Release";
          $env:PUBLISH_BINARY = "true";
          $env:PUBLISH_DIR = "nightlies/";
          $env:VERSION_TAG = "$(Get-Date -UFormat "%Y%m%d")";
        }
        true;
  - ps: >
        if ("$env:APPVEYOR_REPO_TAG" -eq "true") {
          $env:BUILD_TYPE = "Release";
          $env:PUBLISH_BINARY = "true";
          $env:PUBLISH_DIR = "releases/${env:APPVEYOR_REPO_TAG_NAME}/";
          $env:VERSION_TAG = "";
          $env:CI_REF = "refs/tags/${env:APPVEYOR_REPO_TAG_NAME}";
        }
        true;

  - ps: $env:BUILD_SWITCHES = "-DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DVERSION_TAG=%VERSION_TAG% -DCPACK_GENERATOR=ZIP;NSIS -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain-msvc.cmake"
  - ps: >
        if ("$env:BUILD_TYPE" -eq "Release") {
          $env:BUILD_SWITCHES = "${env:BUILD_SWITCHES} -DWITH_EDITOR_SLF=ON";
        }
        true;

  - ps: $env:CLOUDSDK_CORE_DISABLE_PROMPTS = 1

  - cmd: echo "%CMAKE_GENERATOR% %CMAKE_GENERATOR_PLATFORM%"

  - cmd: echo "%PUBLISH_BINARY%"
  - cmd: echo "%PUBLISH_DIR%"
  - cmd: echo "%BUILD_SWITCHES%"

install:
  - ps: $rustVersion = Get-Content .\rust-toolchain -Raw
  - ps: $env:RUSTUP_TOOLCHAIN = "${rustVersion}-${env:RUST_TARGET}";

  - cmd: curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - cmd: rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

  - ps: (New-Object Net.WebClient).DownloadFile("https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-299.0.0-windows-x86.zip", "${env:TEMP}\google-cloud.zip")
  - ps: Expand-Archive "${env:TEMP}\google-cloud.zip" -DestinationPath "${env:TEMP}"
  - ps: $env:PATH = "${env:PATH};${env:TEMP}\google-cloud-sdk\bin"

  - cmd: echo "%RUSTUP_TOOLCHAIN%"
  - cmd: rustc -V
  - cmd: cargo -V
  - cmd: cmake --version
  - cmd: gcloud version

before_build:
  - cmd: mkdir ci-build
  - cmd: cd ci-build
  - cmd: cmake %BUILD_SWITCHES% ..

build_script:
  - ps: cmake --build c:\projects\ja2-stracciatella\ci-build --target ALL_BUILD --config ${env:BUILD_TYPE}

test_script:
  - cmd: cmake --build . --target cargo-test
  - cmd: cd %BUILD_TYPE%
  - cmd: ja2.exe -unittests
  - cmd: ja2-launcher.exe -help

after_test:
  - ps: cmake --build c:\projects\ja2-stracciatella\ci-build --target package
  - ps: cd c:\projects\ja2-stracciatella
  - ps: bash .ci\ci-publish.sh

artifacts:
  - path: ci-build\ja2-stracciatella_*
